from tkinter import *
root=Tk()
l1=Label(root,text="username")
l2=Label(root,text="password")
e1=Entry(root)
e2=Entry(root)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
b1=Button(root,text="submit",fg="red",bg="black")
b1.grid(row=2,column=1)
root.mainloop()