from tkinter import *
root=Tk()
def s():
    print("hlw")
m1=Menu(root)
submenu=Menu(m1)
root.config(menu=m1)
submenu=Menu(m1)
m1.add_cascade(label="abc",menu=submenu)
submenu.add_command(label="s")
submenu.add_command(label="a")
submenu.add_separator()
submenu.add_command(label="j")
submenu.add_command(label="i")
m2=Menu(root)
m1.add_cascade(label="f1",menu=m2)
m2.add_command(label="t",command=s)
m2.add_command(labe="close",command=quit)
root.mainloop()